#!/bin/bash

# Add a login path to your database. This is a one time setting.

# mysql_config_editor set -G blocks -h <db-host> -u <db-user> -p

mysqldump --login-path=blocks --compact --single-transaction \
    xcosblocks > xcosblocks-dump.sql

