--- Dockerfile	2025-08-13 07:39:33.842715454 +0530
+++ Dockerfile.1	2025-08-13 07:39:39.070338013 +0530
@@ -120,7 +120,7 @@
 COPY . .
 
 # Configure venv and sqlite3
-RUN ./install.sh
+RUN ./install.sh prod
 
 # Cleanup
 RUN apt-get autoremove -qq --purge gawk python3-pip python3-venv wget xz-utils
@@ -173,4 +173,4 @@
 
 WORKDIR ${XCOS_DIR}
 
-CMD ["./run.sh"]
+CMD ["./run.sh", "prod"]
