--- Dockerfile	2024-10-14 15:28:16.972057714 +0530
+++ Dockerfile.1	2024-10-14 15:28:43.415609556 +0530
@@ -119,7 +119,7 @@
 COPY . .
 
 # Configure venv and sqlite3
-RUN ./install.sh
+RUN ./install.sh prod
 
 # For localhost only
 RUN echo 'WDS_SOCKET_PORT=80' > eda-frontend/.env.local
@@ -173,4 +173,4 @@
 
 WORKDIR ${XCOS_DIR}
 
-CMD ["./run.sh"]
+CMD ["./run.sh", "prod"]
