--- Dockerfile	2025-07-04 16:16:28.040919228 +0530
+++ Dockerfile.1	2025-07-04 16:19:16.930142599 +0530
@@ -119,7 +119,7 @@
 COPY . .
 
 # Configure venv and sqlite3
-RUN ./install.sh
+RUN ./install.sh prod
 
 # For localhost only
 RUN echo 'WDS_SOCKET_PORT=80' > eda-frontend/.env.local
@@ -173,4 +173,4 @@
 
 WORKDIR ${XCOS_DIR}
 
-CMD ["./run.sh"]
+CMD ["./run.sh", "prod"]
