# Generated by Django 4.2.22 on 2025-08-14 07:03

from django.db import migrations, models
import saveAPI.models


class Migration(migrations.Migration):

    dependencies = [
        ('saveAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statesave',
            name='base64_image',
            field=models.ImageField(null=True, storage=saveAPI.models.get_file_storage, upload_to='simulation_images'),
        ),
    ]
