# Generated by Django 4.2.22 on 2025-08-14 07:03

from django.db import migrations, models
import simulationAPI.models


class Migration(migrations.Migration):

    dependencies = [
        ('simulationAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(storage=simulationAPI.models.get_task_file_storage, upload_to=''),
        ),
    ]
