#!/bin/bash

# Configuration
DOCKER="podman"
IMAGE="docker.io/fossee/osdag:prod"
CONTAINER="osdag"

PORT=9002
ENV_HOST="172.17.0.1"
ENV_USR="osdag"
ENV_PSWD="fossee"
ENV_DB="osdag"

ENV_VARS=(
  ENV_HOST
  ENV_USR
  ENV_PSWD
  ENV_DB
)
ENV_VALS=(
  "$ENV_HOST"
  "$ENV_USR"
  "$ENV_PSWD"
  "$ENV_DB"
)
HOST_PORTS=($PORT)
DOCKER_PORTS=(80)
# End Configuration
