#!/bin/bash

# Configuration
IMAGE="docker.io/fossee/scilab:prod-xcosblocks"
CONTAINER="xcosblocks"

PORT=9000
SQLITE_FILE=~/Downloads/fossee/xcos/xcosblocks.sqlite3
ENV_FILE=~/Downloads/fossee/xcos/env.production

HOST_PORTS=($PORT)
DOCKER_PORTS=(80)
HOST_FILES=($SQLITE_FILE $ENV_FILE)
DOCKER_FILES=(/root/xcosblocks/xcosblocks.sqlite3 /root/xcosblocks/.env)
# End Configuration
