# Generated by Django 4.2.22 on 2025-07-02 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockPrefix',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlockType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField()),
                ('blocktype', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blocktype')),
            ],
        ),
        migrations.CreateModel(
            name='NewBlock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('block_name', models.CharField(max_length=200, null=True, unique=True)),
                ('initial_display_parameter', models.CharField(blank=True, max_length=100, null=True)),
                ('simulation_function', models.CharField(blank=True, max_length=100, null=True)),
                ('block_image_path', models.CharField(blank=True, max_length=100, null=True)),
                ('block_width', models.IntegerField(default=40)),
                ('block_height', models.IntegerField(default=40)),
                ('super_block', models.CharField(max_length=10000, null=True)),
                ('blockprefix', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.blockprefix')),
                ('categories', models.ManyToManyField(to='xcosblocks.category')),
                ('main_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.category')),
            ],
        ),
        migrations.CreateModel(
            name='ParameterDataType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewBlockPort',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('port_order', models.IntegerField()),
                ('port_name', models.CharField(max_length=100)),
                ('port_number', models.CharField(max_length=10)),
                ('port_x', models.IntegerField(default=1)),
                ('port_y', models.IntegerField(default=1)),
                ('port_orientation', models.CharField(max_length=100)),
                ('port_part', models.IntegerField(default=1)),
                ('port_dmg', models.IntegerField(default=1)),
                ('port_type', models.CharField(max_length=100)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='xcosblocks.newblock')),
            ],
        ),
        migrations.CreateModel(
            name='NewBlockParameter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('p_order', models.IntegerField()),
                ('p_label', models.CharField(max_length=100)),
                ('p_help', models.CharField(blank=True, max_length=100, null=True)),
                ('p_value_initial', models.CharField(blank=True, max_length=100)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='xcosblocks.newblock')),
                ('p_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='xcosblocks.parameterdatatype')),
            ],
        ),
        migrations.AddConstraint(
            model_name='newblockport',
            constraint=models.UniqueConstraint(fields=('block', 'port_order'), name='unique_blocktemp_port_order'),
        ),
        migrations.AddConstraint(
            model_name='newblockparameter',
            constraint=models.UniqueConstraint(fields=('block', 'p_order'), name='unique_block_p_order'),
        ),
        migrations.AddConstraint(
            model_name='newblock',
            constraint=models.UniqueConstraint(fields=('main_category', 'name'), name='unique_main_category_name'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('blocktype', 'name'), name='unique_blocktype_name'),
        ),
    ]
